export const videoDimensions = { width: 1920, height: 1080 };

export const API_RESPONSE = [
  {
    id: "66fa5ef507c4e2d6ead907e0",
    badges: {
      attachmentsByType: {
        maskedForPurpose: {
          board: 0,
          card: 0,
        },
      },
      externalSource: null,
      location: false,
      votes: 0,
      viewingMemberVoted: false,
      subscribed: false,
      attachments: 1,
      fogbugz: "",
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      description: false,
      due: null,
      dueComplete: false,
      lastUpdatedByAi: false,
      start: null,
    },
    checkItemStates: [],
    closed: false,
    dueComplete: false,
    dateLastActivity: "2024-10-07T10:28:13.019Z",
    desc: "",
    descData: {
      emoji: {},
    },
    due: null,
    dueReminder: null,
    email: null,
    idBoard: "66fa5dae4c89dcd861b279d9",
    idChecklists: [],
    idList: "66fa5dcc77e666bd2dc61f67",
    idMembers: [],
    idMembersVoted: [],
    idShort: 3,
    idAttachmentCover: "6703b79f49c66f0edb97ede3",
    labels: [],
    idLabels: [],
    manualCoverAttachment: true,
    name: "Done with testing",
    pinned: false,
    pos: 16384,
    shortLink: "3KbfMylo",
    shortUrl: "masked for purpose!",
    start: null,
    subscribed: false,
    url: "masked for purpose!",
    cover: {
      idAttachment: "6703b79f49c66f0edb97ede3",
      color: null,
      idUploadedBackground: null,
      size: "normal",
      brightness: "dark",
      idPlugin: null,
    },
    isTemplate: false,
    cardRole: null,
  },
  {
    id: "6708cab41a925ace38062005",
    badges: {
      attachmentsByType: {
        maskedForPurpose: {
          board: 0,
          card: 0,
        },
      },
      externalSource: null,
      location: false,
      votes: 0,
      viewingMemberVoted: false,
      subscribed: false,
      attachments: 0,
      fogbugz: "",
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      description: false,
      due: null,
      dueComplete: false,
      lastUpdatedByAi: false,
      start: null,
    },
    checkItemStates: [],
    closed: false,
    dueComplete: false,
    dateLastActivity: "2024-10-11T17:02:35.197Z",
    desc: "",
    descData: {
      emoji: {},
    },
    due: null,
    dueReminder: null,
    email: null,
    idBoard: "66fa5dae4c89dcd861b279d9",
    idChecklists: [],
    idList: "66fa5dcc77e666bd2dc61f67",
    idMembers: [],
    idMembersVoted: [],
    idShort: 19,
    idAttachmentCover: null,
    labels: [],
    idLabels: [],
    manualCoverAttachment: false,
    name: "Test with custom data",
    pinned: false,
    pos: 24576,
    shortLink: "ydA2h5Rk",
    shortUrl: "masked for purpose!",
    start: null,
    subscribed: false,
    url: "masked for purpose!",
    cover: {
      idAttachment: null,
      color: null,
      idUploadedBackground: null,
      size: "normal",
      brightness: "dark",
      idPlugin: null,
    },
    isTemplate: false,
    cardRole: null,
  },
  {
    id: "66feb5f7b5deb90872fe9e93",
    badges: {
      attachmentsByType: {
        maskedForPurpose: {
          board: 0,
          card: 0,
        },
      },
      externalSource: null,
      location: false,
      votes: 0,
      viewingMemberVoted: false,
      subscribed: false,
      attachments: 0,
      fogbugz: "",
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      description: false,
      due: null,
      dueComplete: false,
      lastUpdatedByAi: false,
      start: null,
    },
    checkItemStates: [],
    closed: false,
    dueComplete: false,
    dateLastActivity: "2024-10-07T10:28:01.118Z",
    desc: "",
    descData: {
      emoji: {},
    },
    due: null,
    dueReminder: null,
    email: null,
    idBoard: "66fa5dae4c89dcd861b279d9",
    idChecklists: [],
    idList: "66fa5dcc77e666bd2dc61f67",
    idMembers: [],
    idMembersVoted: [],
    idShort: 10,
    idAttachmentCover: null,
    labels: [
      {
        id: "6700d442470c156fc96e1060",
        idBoard: "66fa5dae4c89dcd861b279d9",
        idOrganization: "66fa5dad89dcca4dc191c028",
        name: "Task",
        nodeId:
          "ari:cloud:trello::label/workspace/66fa5dad89dcca4dc191c028/6700d442470c156fc96e1060",
        color: "yellow_dark",
        uses: 8,
      },
    ],
    idLabels: ["6700d442470c156fc96e1060"],
    manualCoverAttachment: false,
    name: "Try to add more triggers, and changes existing with better",
    pinned: false,
    pos: 32768,
    shortLink: "B8ZLpA95",
    shortUrl: "masked for purpose!",
    start: null,
    subscribed: false,
    url: "masked for purpose!",
    cover: {
      idAttachment: null,
      color: null,
      idUploadedBackground: null,
      size: "normal",
      brightness: "dark",
      idPlugin: null,
    },
    isTemplate: false,
    cardRole: null,
  },
];
